### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by fmoo** [teepark/python-lzf#2]
On py3+, setup.py fails installing with pip with a SyntaxError since paver-minilib.zip uses a print statement

```
Downloading/unpacking python-lzf
  Downloading python-lzf-0.2.1.tar.gz
  Running setup.py (path:/home/pete/virtualenv/py33/build/python-lzf/setup.py) egg_info for package python-lzf
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/pete/virtualenv/py33/build/python-lzf/setup.py", line 6, in <module>
        import paver.tasks
      File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
      File "paver-minilib.zip/paver/tasks.py", line 69
        print output
                   ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/pete/virtualenv/py33/build/python-lzf/setup.py", line 6, in <module>

    import paver.tasks

  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked

  File "paver-minilib.zip/paver/tasks.py", line 69

    print output

               ^

SyntaxError: invalid syntax
```

**Comment by mitchellrj** [comment]
@teepark: Could you please cut a new release for PyPI with this fix? Having to install from source repositories is not ideal.
